# Generated by Django 2.2.10 on 2020-03-07 00:36

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('applicant', '0002_auto_20200306_0606'),
    ]

    operations = [
        migrations.RenameModel(
            old_name='Profile',
            new_name='Profileuser',
        ),
    ]
