# Generated by Django 2.2.10 on 2020-03-07 00:56

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('applicant', '0004_profile'),
    ]

    operations = [
        migrations.DeleteModel(
            name='Profileuser',
        ),
    ]
