# Generated by Django 2.2.10 on 2020-03-07 00:57

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('applicant', '0005_delete_profileuser'),
    ]

    operations = [
        migrations.DeleteModel(
            name='Profile',
        ),
    ]
