# Generated by Django 2.2.10 on 2020-03-18 18:28

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('applicant', '0005_auto_20200318_2022'),
    ]

    operations = [
        migrations.AlterField(
            model_name='contacts',
            name='email',
            field=models.CharField(blank=True, max_length=50),
        ),
        migrations.AlterField(
            model_name='contacts',
            name='phone',
            field=models.PositiveIntegerField(blank=True),
        ),
    ]
