# Generated by Django 2.2.10 on 2020-04-16 19:49

import company.models
from django.conf import settings
from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    initial = True

    dependencies = [
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
    ]

    operations = [
        migrations.CreateModel(
            name='Send_Email',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('username', models.CharField(blank=True, max_length=50, null=True)),
                ('email', models.EmailField(blank=True, max_length=50, null=True)),
                ('content', models.CharField(blank=True, max_length=350, null=True)),
            ],
        ),
        migrations.CreateModel(
            name='Notification',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('verb', models.CharField(max_length=100)),
                ('description', models.TextField()),
                ('read', models.BooleanField(default=False)),
                ('post', models.IntegerField()),
                ('applicant', models.IntegerField()),
                ('receiver', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to=settings.AUTH_USER_MODEL)),
            ],
        ),
        migrations.CreateModel(
            name='Match_Results',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('resume', models.CharField(blank=True, max_length=100, null=True, verbose_name='resume')),
                ('app_email', models.CharField(blank=True, max_length=50, verbose_name='email')),
                ('job_id', models.CharField(blank=True, max_length=100, null=True, verbose_name='the job')),
                ('skills_rslt', models.CharField(blank=True, max_length=1000, null=True, verbose_name='match result')),
                ('status', models.CharField(blank=True, max_length=100, null=True, verbose_name='status')),
                ('content', models.CharField(blank=True, max_length=300, null=True)),
                ('aplcnt', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to=settings.AUTH_USER_MODEL)),
            ],
        ),
        migrations.CreateModel(
            name='CreatePost',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('jobtitle', models.CharField(blank=True, max_length=50)),
                ('job_description', models.CharField(blank=True, max_length=500)),
                ('joblocation', models.CharField(blank=True, max_length=50)),
                ('city', models.CharField(blank=True, max_length=50)),
                ('Area', models.CharField(blank=True, max_length=50)),
                ('careerlevel', models.CharField(blank=True, max_length=50)),
                ('year_of_experience', models.CharField(blank=True, max_length=50)),
                ('salary_range1', models.CharField(blank=True, max_length=50)),
                ('salary_range2', models.CharField(blank=True, max_length=50)),
                ('num_vacancies', models.TextField(blank=True, max_length=50)),
                ('jobtype', models.CharField(blank=True, max_length=50)),
                ('image', models.ImageField(blank=True, upload_to=company.models.upload_location)),
                ('skills', models.CharField(blank=True, max_length=500)),
                ('deadline', models.DateField(blank=True)),
                ('status', models.CharField(default='Publishing', max_length=10)),
                ('date_published', models.DateTimeField(auto_now_add=True, verbose_name='date published')),
                ('date_updated', models.DateTimeField(auto_now=True, verbose_name='date updated')),
                ('slug', models.SlugField(blank=True)),
                ('author', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to=settings.AUTH_USER_MODEL)),
            ],
        ),
    ]
