# Generated by Django 2.2.10 on 2020-04-04 22:06

from django.conf import settings
from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
        ('company', '0002_createpost_image'),
    ]

    operations = [
        migrations.AlterField(
            model_name='createpost',
            name='deadline',
            field=models.DateField(blank=True),
        ),
        migrations.CreateModel(
            name='Match_Results',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('resume', models.CharField(blank=True, max_length=100, null=True, verbose_name='resume')),
                ('job_id', models.CharField(blank=True, max_length=100, null=True, verbose_name='the job')),
                ('skills_rslt', models.CharField(blank=True, max_length=1000, null=True, verbose_name='match result')),
                ('status', models.CharField(blank=True, max_length=100, null=True, verbose_name='status')),
                ('author', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to=settings.AUTH_USER_MODEL)),
            ],
        ),
    ]
