# Generated by Django 2.2.10 on 2020-02-28 17:42

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('company', '0002_jobrole'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='jobrole',
            name='id',
        ),
        migrations.AlterField(
            model_name='createpost',
            name='rolejob',
            field=models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='company.jobRole'),
        ),
        migrations.AlterField(
            model_name='jobrole',
            name='name',
            field=models.CharField(max_length=50, primary_key=True, serialize=False),
        ),
    ]
