# Generated by Django 2.2.10 on 2020-02-25 16:58

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('company', '0002_listshow'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='createpost',
            name='company_name',
        ),
        migrations.DeleteModel(
            name='Listshow',
        ),
    ]
