# Generated by Django 2.2.10 on 2020-02-26 16:34

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('company', '0002_auto_20200226_1819'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='createpost',
            name='deadline',
        ),
    ]
