# Generated by Django 2.2.10 on 2020-02-28 19:01

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('company', '0003_auto_20200228_1942'),
    ]

    operations = [
        migrations.CreateModel(
            name='relatedIndustry',
            fields=[
                ('name', models.CharField(max_length=50, primary_key=True, serialize=False)),
            ],
        ),
    ]
