# Generated by Django 2.2.11 on 2020-04-06 15:07

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('company', '0003_auto_20200405_0006'),
    ]

    operations = [
        migrations.RenameField(
            model_name='match_results',
            old_name='author',
            new_name='aplcnt',
        ),
        migrations.AddField(
            model_name='match_results',
            name='app_email',
            field=models.CharField(blank=True, max_length=50, verbose_name='email'),
        ),
    ]
