# Generated by Django 2.2.11 on 2020-03-23 20:35

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('company', '0003_auto_20200323_2118'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='createpost',
            name='deadline',
        ),
    ]
