# Generated by Django 2.2.11 on 2020-03-23 20:49

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('company', '0004_remove_createpost_deadline'),
    ]

    operations = [
        migrations.AddField(
            model_name='createpost',
            name='deadline',
            field=models.DateTimeField(blank=True, null=True, verbose_name='deadline'),
        ),
    ]
