# Generated by Django 2.2.10 on 2020-02-27 12:05

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('company', '0004_createpost_deadline'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='createpost',
            name='deadline',
        ),
    ]
