# Generated by Django 2.2.11 on 2020-04-06 21:05

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('company', '0005_match_results_content'),
    ]

    operations = [
        migrations.CreateModel(
            name='Send_Email',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('username', models.CharField(blank=True, max_length=50, null=True)),
                ('email', models.EmailField(blank=True, max_length=50, null=True)),
                ('content', models.CharField(blank=True, max_length=350, null=True)),
            ],
        ),
    ]
