# Generated by Django 2.2.11 on 2020-03-24 17:08

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('company', '0006_auto_20200323_2253'),
    ]

    operations = [
        migrations.AlterField(
            model_name='createpost',
            name='deadline',
            field=models.DateField(blank=True, verbose_name='deadline'),
        ),
    ]
