# Generated by Django 2.2.11 on 2020-03-24 17:11

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('company', '0007_auto_20200324_1908'),
    ]

    operations = [
        migrations.AlterField(
            model_name='createpost',
            name='deadline',
            field=models.DateTimeField(blank=True, verbose_name='deadline'),
        ),
    ]
