# Generated by Django 2.2.11 on 2020-04-11 21:42

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('company', '0007_notification'),
    ]

    operations = [
        migrations.AddField(
            model_name='notification',
            name='applicant',
            field=models.IntegerField(default=3),
            preserve_default=False,
        ),
        migrations.AddField(
            model_name='notification',
            name='post',
            field=models.IntegerField(default=3),
            preserve_default=False,
        ),
    ]
