# Generated by Django 2.2.11 on 2020-04-15 15:28

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('company', '0008_auto_20200411_2342'),
    ]

    operations = [
        migrations.AlterField(
            model_name='match_results',
            name='job_id',
            field=models.IntegerField(blank=True, null=True, verbose_name='the job'),
        ),
    ]
