# Generated by Django 2.2.11 on 2020-04-16 20:01

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('company', '0009_auto_20200415_1728'),
    ]

    operations = [
        migrations.CreateModel(
            name='category',
            fields=[
                ('name', models.TextField(max_length=100, primary_key=True, serialize=False)),
            ],
        ),
        migrations.AddField(
            model_name='createpost',
            name='category',
            field=models.ForeignKey(default='programmer', on_delete=django.db.models.deletion.CASCADE, to='company.category'),
            preserve_default=False,
        ),
    ]
