# Generated by Django 2.2.11 on 2020-05-18 21:26

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('company', '0011_auto_20200417_1612'),
    ]

    operations = [
        migrations.AlterField(
            model_name='match_results',
            name='skills_rslt',
            field=models.FloatField(blank=True, max_length=1000, null=True, verbose_name='match result'),
        ),
    ]
