# Generated by Django 2.2.10 on 2020-05-15 20:07

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('company', '0012_auto_20200514_1511'),
    ]

    operations = [
        migrations.AddField(
            model_name='category',
            name='jobno',
            field=models.IntegerField(null=True),
        ),
    ]
