# Generated by Django 2.2.11 on 2020-05-22 19:30

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('company', '0012_auto_20200518_2326'),
        ('company', '0013_category_jobno'),
    ]

    operations = [
    ]
