# Generated by Django 2.2.11 on 2020-05-23 15:19

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('company', '0014_merge_20200522_2130'),
    ]

    operations = [
        migrations.AlterField(
            model_name='category',
            name='jobno',
            field=models.IntegerField(blank=True, null=True),
        ),
    ]
