# Generated by Django 2.2.11 on 2020-05-27 01:04

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('company', '0015_auto_20200523_1719'),
    ]

    operations = [
        migrations.AddField(
            model_name='createpost',
            name='views',
            field=models.IntegerField(default=0),
        ),
    ]
