# Generated by Django 2.2.11 on 2020-06-10 16:04

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('company', '0016_createpost_views'),
    ]

    operations = [
        migrations.CreateModel(
            name='Schdule',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('username', models.CharField(max_length=100)),
                ('jobname', models.CharField(max_length=100)),
                ('date_schdule', models.DateTimeField()),
                ('time_schdule', models.TimeField()),
            ],
        ),
    ]
