# Generated by Django 2.2.11 on 2020-06-12 22:42

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('company', '0019_auto_20200613_0021'),
    ]

    operations = [
        migrations.AlterField(
            model_name='schdule',
            name='username',
            field=models.CharField(max_length=100),
        ),
    ]
