# Generated by Django 2.2.11 on 2020-06-12 22:59

from django.conf import settings
from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('company', '0020_auto_20200613_0042'),
    ]

    operations = [
        migrations.AlterField(
            model_name='schdule',
            name='username',
            field=models.OneToOneField(on_delete=django.db.models.deletion.CASCADE, related_name='applicant_user', to=settings.AUTH_USER_MODEL),
        ),
    ]
