# Generated by Django 2.2.11 on 2020-06-12 23:20

from django.conf import settings
from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('company', '0022_auto_20200613_0116'),
    ]

    operations = [
        migrations.AlterField(
            model_name='match_results',
            name='aplcnt',
            field=models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to=settings.AUTH_USER_MODEL),
        ),
    ]
