# Generated by Django 2.2.10 on 2020-06-18 00:41

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('company', '0024_auto_20200613_0152'),
    ]

    operations = [
        migrations.AlterField(
            model_name='createpost',
            name='image',
            field=models.CharField(max_length=5000),
        ),
    ]
