# Generated by Django 2.2.10 on 2020-07-19 23:12

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('company', '0026_match_results_matched_skills'),
    ]

    operations = [
        migrations.AddField(
            model_name='match_results',
            name='not_matched_skills',
            field=models.CharField(blank=True, max_length=1000, null=True, verbose_name='n_Skills'),
        ),
        migrations.AlterField(
            model_name='match_results',
            name='matched_skills',
            field=models.CharField(blank=True, max_length=1000, null=True, verbose_name='f_Skills'),
        ),
    ]
