# Generated by Django 2.2.11 on 2020-07-19 19:45

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('company', '0028_match_results_company'),
    ]

    operations = [
        migrations.AddField(
            model_name='schdule',
            name='author',
            field=models.CharField(default=1, max_length=100),
            preserve_default=False,
        ),
    ]
