# Generated by Django 2.2.10 on 2020-07-20 22:22

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('company', '0029_schdule_author'),
        ('company', '0028_match_results_experience'),
    ]

    operations = [
    ]
