# Generated by Django 2.2.11 on 2020-07-25 21:36

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('company', '0030_merge_20200721_0022'),
    ]

    operations = [
        migrations.AlterModelOptions(
            name='createpost',
            options={'ordering': ['-date_published']},
        ),
    ]
