# Generated by Django 2.2.10 on 2020-02-20 01:35

import company.models
from django.conf import settings
from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    initial = True

    dependencies = [
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
    ]

    operations = [
        migrations.CreateModel(
            name='CreatePost',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('company_name', models.CharField(blank=True, max_length=50)),
                ('jobtitle', models.CharField(blank=True, max_length=50)),
                ('joblocation', models.CharField(blank=True, max_length=50)),
                ('city', models.CharField(blank=True, max_length=50)),
                ('Area', models.CharField(blank=True, max_length=50)),
                ('careerlevel', models.CharField(blank=True, max_length=50)),
                ('year_of_experience', models.CharField(blank=True, max_length=50)),
                ('salary_range', models.CharField(blank=True, max_length=50)),
                ('additional_salary', models.CharField(blank=True, max_length=50)),
                ('num_vacancies', models.TextField(blank=True, max_length=50)),
                ('rolejob', models.CharField(blank=True, max_length=50)),
                ('related_industry', models.CharField(blank=True, max_length=50)),
                ('jobtype', models.CharField(blank=True, max_length=50)),
                ('job_description', models.CharField(blank=True, max_length=500)),
                ('skills', models.CharField(blank=True, max_length=500)),
                ('image', models.ImageField(blank=True, upload_to=company.models.upload_location)),
                ('date_published', models.DateTimeField(auto_now_add=True, verbose_name='date published')),
                ('date_updated', models.DateTimeField(auto_now=True, verbose_name='date updated')),
                ('slug', models.SlugField(blank=True, unique=True)),
                ('author', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to=settings.AUTH_USER_MODEL)),
            ],
        ),
    ]
